### ISSUE TITLE
Design vehicle driving model @AdrianA

### ISSUE THREAD

**Issue by hobogalaxy** [hobogalaxy/ISA#8]
- [x] Sliding vehicle model #9 

- [x] Wheel simulation vehicle model #10 

- [x] Advanced vehicle with steering wheels #14
